// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7_daWmF3A0D1vNB6zjChV7pJg7baJ7V8',
    appId: '1:147612180943:web:e3a3b7dc19015cdd1df2ba',
    messagingSenderId: '147612180943',
    projectId: 'chat-app-fc91e',
    authDomain: 'chat-app-fc91e.firebaseapp.com',
    storageBucket: 'chat-app-fc91e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWajER2PYiVux52HttfHuvNfKaYRoyGBA',
    appId: '1:147612180943:android:5723cb6e7a1420381df2ba',
    messagingSenderId: '147612180943',
    projectId: 'chat-app-fc91e',
    storageBucket: 'chat-app-fc91e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRvZzaCmBBgCkOfxeFCRmPHHvsz-n8GXw',
    appId: '1:147612180943:ios:232f45087d733d601df2ba',
    messagingSenderId: '147612180943',
    projectId: 'chat-app-fc91e',
    storageBucket: 'chat-app-fc91e.appspot.com',
    iosClientId: '147612180943-ciognsst6bo2dh5df4pcu9ckopt34akt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRvZzaCmBBgCkOfxeFCRmPHHvsz-n8GXw',
    appId: '1:147612180943:ios:10262f3e4fa3b6a01df2ba',
    messagingSenderId: '147612180943',
    projectId: 'chat-app-fc91e',
    storageBucket: 'chat-app-fc91e.appspot.com',
    iosClientId: '147612180943-rjmleblf8mm1tj6pev9216pup8n0fpu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
